export const en = {
  0: 'Log in',
  1: 'Sign Up',
  2: 'beep - Log in',
  3: 'Meet beep',
  4: 'The application allows you to upload videos that are processed on the server, censoring inappropriate language. After processing, users can view where inappropriate language was censored and download a separate audio track with the resulting outcome.',
  5: 'Upload video',
  6: 'beep - Sign Up',
  7: 'Log In',
  8: 'Password',
  9: 'Create Account',
  10: 'Sign Up',
  11: 'Username',
  12: 'Username or email',
  13: 'The password must be at least 8 characters long.',
  14: 'The username must be between 4 and 30 characters and can only include letters and numbers.',
  15: 'This field is required.',
  16: 'The email address specified is incorrect.',
  17: 'Invalid username specified.',
  18: 'The password must be at least 8 characters long.',
  19: 'The specified username is invalid; it must be between 4 and 30 characters long and can only include letters and numbers.',
  20: 'Something went wrong. Please try again later.',
  21: 'Bad email or password.',
  22: 'Username already registered.',
  23: 'Email already registered.',
  24: 'beep - Presets',
  25: 'Privacy Policy',
  26: 'Log out',
  27: 'Presets',
  28: 'Projects',
  29: 'beep - Projects',
  30: 'Create project',
  31: 'Creating a project',
  32: 'The project name must be unique and contain from 1 to 255 characters.',
  33: 'Project name',
  34: 'Next',
  35: 'beep - Upload file',
  36: 'Download file',
  37: 'Video Processing',
  38: 'Project creation failed. Try again.',
  39: 'The project has been created successfully. You are redirected to the video upload page.',
};