export const en = {
  0: 'Log in',
  1: 'Sign Up',
  2: 'get-beeped - Log in',
  3: 'Meet beep',
  4: 'The service helps you automatically mute profanity or any unwanted words in your videos and audios. Just upload the file and we\'ll upload it. After processing, you will be able to see exactly where the corrections were made and download the finished file. Fast, simple and convenient!',
  5: 'Upload video',
  6: 'get-beeped - Sign Up',
  7: 'Log In',
  8: 'Password',
  9: 'Create Account',
  10: 'Sign Up',
  11: 'Username',
  12: 'Username or email',
  13: 'The password must be at least 8 characters long.',
  14: 'The username must be between 4 and 30 characters and can only include letters and numbers.',
  15: 'This field is required.',
  16: 'The email address specified is incorrect.',
  17: 'Invalid username specified.',
  18: 'The password must be at least 8 characters long.',
  19: 'The specified username is invalid; it must be between 4 and 30 characters long and can only include letters and numbers.',
  20: 'Something went wrong. Please try again later.',
  21: 'Bad email or password.',
  22: 'Username already registered.',
  23: 'Email already registered.',
  24: 'get-beeped - Presets',
  25: 'Privacy Policy',
  26: 'Log out',
  27: 'Presets',
  28: 'Projects',
  29: 'get-beeped - Projects',
  30: 'Create project',
  31: 'Creating a project',
  32: 'The project name must contain from 1 to 255 characters.',
  33: 'Project name',
  34: 'Next',
  35: 'get-beeped - Upload file',
  36: 'Download file',
  37: 'Video Processing',
  38: 'Project creation failed. Try again.',
  39: 'The project has been created successfully. You are redirected to the video upload page.',
  40: 'You can send your questions and suggestions to the email address:',
  41: 'We are always ready to help you!',
  42: 'Legal information',
  43: 'Self-employed {{value1}}',
  44: 'TIN: {{value1}}',
  45: 'Tablet and mobile versions are not available at this time.',
  46: 'By registering on our website, you automatically confirm that you have read our terms and conditions',
  47: 'offers',
  48: 'and you accept them. Please read the terms and conditions carefully before completing your registration.',
  49: 'Enter the code we sent to your email to verify your account.',
  50: 'Verify account',
  51: 'Send new code',
  52: 'You can resend the code via {{value1}}',
  53: 'The code has been successfully sent to your email.',
  54: 'The user is not active. Please confirm your email address.',
  55: 'Email confirmed, user activated.',
  56: 'The verification code is invalid or the code has expired.',
  57: 'User not found.',
  58: 'Back',
  59: 'Next',
  60: 'Searching for a project...',
  61: '{{value1}}h {{value2}}m',
  62: 'Create a new project',
  63: 'Ready',
  64: 'Processing',
  65: 'Processing error',
  66: 'The file is being prepared for processing',
  67: 'Created',
  68: 'Project',
  69: 'Project status',
  70: 'Project Information',
  71: 'View Page',
  72: 'Upload file',
  73: 'Project name:',
  74: 'Project type:',
  75: 'Project ID:',
  76: 'Status:',
  77: 'Until processing is completed:',
  78: 'Start processing',
  79: 'The file is loading...',
  80: 'Drag the file here',
  81: 'Drag the file here or click the button below to select it on your computer',
  82: 'File uploaded successfully. To select a different file, drag and drop here or click the button below to select it on your computer',
  83: 'Select file',
  84: 'Select another file',
  85: 'Supported formats:',
  86: 'The file is currently being downloaded. Please do not leave this page until the video has finished loading.',
  87: 'Please do not leave this page until the file has finished downloading.',
  88: 'Download file',
  89: 'get-beeped - Your project',
  90: 'get-beeped - View Page',
  91: 'Need to top up minutes account or get a subscription.',
  92: 'Chat with support',
  93: 'get-beeped - Buy minutes',
  94: 'Buying minutes',
  95: 'A few minutes',
  96: 'Suitable for short videos',
  97: 'Number of minutes:',
  98: 'Buy for {{value1}}₽',
  99: 'Will you renew?',
  100: 'Beep podcast',
  101: 'Solid pack of minutes',
  102: 'For good home video',
  103: 'Public ',
  104: ' agreement for the provision of services',
  105: 'get-beeped - Prices',
  106: 'Prices',
  107: 'Privacy Policy',
  108: 'Video',
  109: 'Audio',
  110: 'Unmute',
  111: 'Mute',
};